FinanceApp/Models/DashboardViewModel.cs
namespace FinanceApp.Models
{
    public class DashboardViewModel
    {
        public decimal FullBudget { get; set; }

        public decimal CurrentBudget { get; set; }

        public decimal EstimatedBudget { get; set; }

        public string Currency { get; set; }

        public IEnumerable<PaymentTypeViewModel> PaymentsInfo { get; set; }
    }
}

FinanceApp/Controllers/DashboardController.cs
using FinanceApp.Core.Common;
using FinanceApp.Core.Contracts;
using FinanceApp.Core.Helpers;
using FinanceApp.Infrastructure.Models;
using FinanceApp.Models;
using Ganss.XSS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinanceApp.Controllers
{
    /// <summary>
    /// Controller for the Dashboard page
    /// </summary>
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IPaymentService paymentService;
        private readonly IPaymentTypeService paymentTypeService;
        private readonly UserManager<User> userManager;

        private decimal? budget;
        private string currency;

        public DashboardController(IPaymentService _paymentService, IPaymentTypeService _paymentTypeService, UserManager<User> _userManager)
        {
            paymentService = _paymentService;
            paymentTypeService = _paymentTypeService;
            userManager = _userManager;

        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await userManager.GetUserAsync(User);
            budget = await paymentService.GetUsersFullMonthlyBudget();
            currency = await paymentService.GetUsersCurrency();
            if (budget == null || budget == 0 || currency == null)
            {
                return RedirectToAction("MonthlyBudgetForm");
            }
            else
            {
                var currentBudget = await paymentService.GetUsersCurrentBudget();
                var estimatedBudget = await paymentService.GetUsersEstimatedBudget();

                var paymentTypes = await paymentTypeService.GetAllActivePaymentTypes();
                var enumNames = Enum.GetNames(typeof(Currencies));
                var model = new DashboardViewModel()
                {
                    FullBudget = (decimal)budget,
                    CurrentBudget = (decimal)currentBudget,
                    EstimatedBudget = (decimal)estimatedBudget,
                    PaymentsInfo = paymentTypes.Select(pt => new PaymentTypeViewModel
                    {
                        Id = pt.Id,
                        Name = pt.Name,
                        CurrentPayments = pt.Payments.Select(p => new PaymentViewModel
                        {
                            Id = p.Id,
                            Name = p.Name,
                            Description = p.Description,
                            Cost = p.Cost,
                            IsSignular = p.IsSignular,
                            IsPaidFor = p.IsPaidFor,
                            PaymentTypeId = p.PaymentTypeId
                        })

                    }),
                    Currency = EnumHelper.GetEnumDescription((Currencies)Array.IndexOf(enumNames, currency))
                };
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult MonthlyBudgetForm()
        {
            var model = new DashboardViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> MonthlyBudgetForm(DashboardViewModel model)
        {
            if (model.FullBudget == 0m || model.Currency == null)
            {
                ModelState.AddModelError("","Invalid budget or currency");
                return View(model);
            }
            await paymentService.SetUsersMonthlyBudget(model.FullBudget);
            await paymentService.SetUsersCurrency(model.Currency);

            return RedirectToAction("Index");
        }

    }
}

FinanceApp/Controllers/PaymentsController.cs
using FinanceApp.Infrastructure.Models;
using FinanceApp.Models;
using FinanceApp.Core.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Ganss.XSS;

namespace FinanceApp.Controllers
{
    /// <summary>
    /// Controller for the Payments pages
    /// </summary>
    [Authorize]
    public class PaymentsController : Controller
    {
        private readonly IPaymentService paymentService;
        private readonly IPaymentTypeService paymentTypeService;
        private readonly UserManager<User> userManager;
        private IHtmlSanitizer sanitizer;

        public PaymentsController(IPaymentService _paymentService, IPaymentTypeService _paymentTypeService, UserManager<User> _userManager)
        {
            paymentService = _paymentService;
            paymentTypeService = _paymentTypeService;
            userManager = _userManager;

            sanitizer = new HtmlSanitizer();
        }
        public async Task<IActionResult> Index()
        {
            var entities = await paymentTypeService.GetAllActivePaymentTypes();
            var models = entities.Select(x => new PaymentTypeViewModel()
            {
                Id = x.Id,
                Name = x.Name
            });

            return View(models);
        }

        public async Task<IActionResult> SelectPaymentType(int id)
        {
            var entity = await paymentTypeService.GetPaymentTypeAsync(id);
            if (entity != null)
            {
                var payments = await paymentService.GetAllActivePaymentsByTypeIdAsync(id);
                var model = new PaymentTypeViewModel()
                {
                    Id = entity.Id,
                    Name = entity.Name,
                    CurrentPayments = payments
                        .Select(p => new PaymentViewModel()
                        {
                            Id = p.Id,
                            Name = p.Name,
                            Description = p.Description,
                            Cost = p.Cost,
                            IsSignular = p.IsSignular,
                            IsPaidFor = p.IsPaidFor,
                        })
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Error", "Home", 
                    new ErrorViewModel() 
                    { 
                        Message = "Payment type not found." 
                    } );
            }
            
        }
        [HttpGet]
        public IActionResult AddCurrentPayment(int id)
        {
            var model = new PaymentViewModel();
            model.PaymentTypeId = id;

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddCurrentPayment(PaymentViewModel model)
        {


            var currentUser = await userManager.GetUserAsync(this.User);
            var entry = new CurrentPayment()
            {
                Name = sanitizer.Sanitize(model.Name),
                Description = sanitizer.Sanitize(model.Description),
                Cost = model.Cost,
                IsSignular = model.IsSignular,
                UserId = currentUser.Id,
                //TODO: Fix in the future. model.PaymentTypeId => model.Id for some reason
                PaymentTypeId = model.Id,
                IsActive = true,
                EntryDate = DateTime.Now,
            };

            await paymentService.AddCurrentPaymentAsync(entry);

            return RedirectToAction("SelectPaymentType", new { id = entry.PaymentTypeId });
        }

        [HttpGet]
        public IActionResult AddPaymentType()
        {
            var model = new PaymentTypeViewModel();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddPaymentType(PaymentTypeViewModel model)
        {
            var currentUser = await userManager.GetUserAsync(this.User);
            var entry = new PaymentType()
            {
                Name = sanitizer.Sanitize(model.Name),
                IsActive = true,
                UserId = currentUser.Id
            };

            await paymentTypeService.AddPaymentTypeAsync(entry);
            var paymentTypes = await paymentTypeService.GetAllActivePaymentTypes();
            var id = paymentTypes.Single(pt => pt.Name == entry.Name).Id;
            return RedirectToAction("SelectPaymentType", new { id });
        }

        [HttpGet]
        public async Task<IActionResult> DeletePaymentType(int id)
        {
            await paymentTypeService.DeletePaymentType(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DeletePayment(int id)
        {
            await paymentService.DeletePayment(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditPaymentType(int id)
        {
            var entity = await paymentTypeService.GetPaymentTypeAsync(id);
            var model = new PaymentTypeViewModel()
            {
                Id = entity.Id,
                Name = entity.Name,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditPaymentType(PaymentTypeViewModel model)
        {
            model.Name = sanitizer.Sanitize(model.Name);

            var entity = await paymentTypeService.GetPaymentTypeAsync(model.Id);
            entity.Name = model.Name;


            await paymentTypeService.SaveChangesToPaymentTypeAsync();

            return RedirectToAction("SelectPaymentType", new { id = model.Id });
        }


        public async Task<IActionResult> PayForPayment(int id)
        {
            await paymentService.PayForPayment(id);

            return RedirectToAction("Index", "Dashboard");
        }

        public async Task<IActionResult> UndoPayment(int id)
        {
            await paymentService.UndoPayment(id);

            return RedirectToAction("Index", "Dashboard");
        }

    }
}

FinanceApp/Controllers/ViewComponents/CurrencyChoicesLoadViewComponent.cs
using FinanceApp.Core.Common;
using FinanceApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System;
using FinanceApp.Core.Helpers;

namespace FinanceApp.Controllers.ViewComponents
{
    public class CurrencyChoicesLoadViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new CurrencyViewModel();
            var enumNames = Enum.GetNames(typeof(Currencies));
            var enumCount = enumNames.Length;
            for (int i = 0; i < enumCount; i++)
            {
                model.CurrencyNames.Add(enumNames[i]);
                model.CurrencyCodes.Add(EnumHelper.GetEnumDescription((Currencies)i));
            }

            return View(model);
        }

    }
}

FinanceApp/Views/Dashboard/Index.cshtml
@model DashboardViewModel

@{
    ViewBag.Title = "Dashboard";
    ViewData["Title"] = ViewBag.Title;
}
<div class="text-center">
    <h1 >Dashboard</h1>
    <hr />
    <div class="list-inline">
        <h3 class="list-inline-item">| Full Budget:</h3>
        <h3 class="list-inline-item">@Model.FullBudget.ToString("F")@Html.Raw(Model.Currency) | </h3>

        <h3 class="list-inline-item">Current Budget:</h3>
        <h3 class="list-inline-item">@Model.CurrentBudget.ToString("F")@Html.Raw(Model.Currency) | </h3>

        <h3 class="list-inline-item">Estimated Budget:</h3>
        <h3 class="list-inline-item">@Model.EstimatedBudget.ToString("F")@Html.Raw(Model.Currency) | </h3>
        @*<div class="vertical list-inline-item"></div>*@
    </div>
    <hr />

    <partial name="_PaymentTypeDisplayPartial" />
</div>

FinanceApp/Views/Dashboard/MonthlyBudgetForm.cshtml
@model DashboardViewModel

@{
    ViewData["Title"] = "Monthly Budget";
}

<h1 class="text-center">@ViewData["Title"]</h1>
<div class="row">
    <div class="col-md-4 offset-md-4">
        <section>
            <form id="account" method="post">
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="text-center mb-3">
                    <label asp-for="@Model.FullBudget" class="form-label">What is your monthly budget?</label>
                    <input asp-for="@Model.FullBudget" class="form-control" autocomplete="username" aria-required="true" />
                    <span asp-validation-for="FullBudget" class="text-danger"></span>
                </div>
                <div class="text-center mb-3">
                    <label asp-for="@Model.Currency" class="form-label">Currency</label>
                    <select asp-for=@Model.Currency class="form-select" aria-label="Currency">
                        <option selected>Select an option</option>
                        @await Component.InvokeAsync("CurrencyChoicesLoad")
                    </select>
                </div>
                <div class="text-center">
                    <button id="login-submit" type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
            
        </section>
    </div>
</div>

FinanceApp/Views/Dashboard/_PaymentTypeDisplayPartial.cshtml
<div class="justify-content-center">
    <div class="w-50 mx-auto">
        @foreach (var paymentType in Model.PaymentsInfo)
        {
            <h3 class="m-2">@paymentType.Name</h3>
            <hr style="margin:auto" />
            <div class="text-start">
                @{
                    var counter = 1;
                    foreach (var payment in paymentType.CurrentPayments)
                    {
                        string isPaid = payment.IsPaidFor ? "Is Paid" : "Is Not Paid";
                        <h4 class="d-inline-block">@counter. @payment.Name | @payment.Cost | @isPaid</h4>
                        if (!payment.IsPaidFor)
                        {
                            <button type="button" class="btn m-lg-2 btn-success btn-outline-secondary rounded-3" style="padding: 0">
                                <a class="nav-link text-white" asp-controller="Payments" asp-action="PayForPayment" asp-route-id=@payment.Id>Pay</a>
                            </button>
                        }
                        else
                        {
                            <button type="button" class="btn m-lg-2 btn-secondary btn-outline-success rounded-3" style="padding: 0">
                                <a class="nav-link text-white" asp-controller="Payments" asp-action="UndoPayment" asp-route-id=@payment.Id>Undo Payment</a>
                            </button>
                        }
                        <br />
                        counter++;
                    }
                }
            </div>
            <hr style="margin:auto" />
        }
    </div>
</div>