FinanceApp/Controllers/HistoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FinanceApp.Models;
using FinanceApp.Core.Contracts;
using Microsoft.AspNetCore.Identity;
using FinanceApp.Infrastructure.Models;

namespace FinanceApp.Controllers
{
    /// <summary>
    /// Controller for the history page
    /// </summary>
    [Authorize]
    public class HistoryController : Controller
    {
        private readonly IHistoryService historyService;
        private readonly IPaymentService paymentService;
        private readonly IPaymentTypeService paymentTypeService;

        public HistoryController(IHistoryService _historyService, IPaymentService _paymentService, IPaymentTypeService _paymentTypeService)
        {
            historyService = _historyService;
            paymentService = _paymentService;
            paymentTypeService = _paymentTypeService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new HistoryViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(HistoryViewModel model)
        {
            var paymentEntities = await historyService.GetHistoryPaymentsByMonthAndYearAsync(model.SearchMonth, model.SearchYear);
            var paymentModels = paymentEntities.Select(e => new PaymentViewModel
            {
                Id = e.Id,
                Name = e.Name,
                Description = e.Description,
                Cost = e.Price,
                IsSignular = e.IsSingular,
                IsPaidFor = e.IsPaidFor,
                PaymentTypeId = e.PaymentTypeId
            });
            var paymentTypeEntities = await Task.FromResult(paymentTypeService
                .GetAllActivePaymentTypes().Result
                .Where(pt => paymentModels
                .Select(pm => pm.PaymentTypeId)
                .Contains(pt.Id))
                .ToArray());
            var historyModel = new HistoryViewModel()
            {
                Result = new DashboardViewModel()
                {
                    PaymentsInfo = paymentTypeEntities.Select(pte => new PaymentTypeViewModel()
                    {
                        Id = pte.Id,
                        Name = pte.Name,
                        CurrentPayments = paymentModels.Where(pm => pm.PaymentTypeId == pte.Id)
                    })
                }
            };
            return View(historyModel);
        }

        [HttpGet]
        public async Task<IActionResult> Undo()
        {
            var paymentEntities = await historyService.GetAllDeletedPayments();
            var paymentModels = paymentEntities.Select(e => new PaymentViewModel
            {
                Id = e.Id,
                Name = e.Name,
                Description = e.Description,
                Cost = e.Cost,
                IsSignular = e.IsSignular,
                IsPaidFor = e.IsPaidFor,
                PaymentTypeId = e.PaymentTypeId
            });
            var paymentTypeEntities = await historyService.GetAllDeletedPaymentTypes();
            var paymentTypeModels = paymentTypeEntities.Select(e => new PaymentTypeViewModel()
            {
                Id= e.Id,
                Name= e.Name
            });
            var UndoModel = new UndoViewModel()
            {
                DeletedPayments = paymentModels,
                DeletedPaymentTypes = paymentTypeModels
            };
            
            return View(UndoModel);
        }

        [HttpGet]
        public async Task<IActionResult> UndoPaymentType(int id)
        {
            var entity = await paymentTypeService.GetInactivePaymentTypeAsync(id);
            await historyService.UndoDeletedPaymentType(entity);

            return RedirectToAction("Undo");
        }

        [HttpGet]
        public async Task<IActionResult> UndoPayment(int id)
        {
            var entity = await paymentService.GetPaymentAsync(id);
            await historyService.UndoDeletedPayment(entity);

            return RedirectToAction("Undo");
        }

    }
}

FinanceApp/Controllers/PaymentsController.cs
using FinanceApp.Infrastructure.Models;
using FinanceApp.Models;
using FinanceApp.Core.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Ganss.XSS;

namespace FinanceApp.Controllers
{
    /// <summary>
    /// Controller for the Payments pages
    /// </summary>
    [Authorize]
    public class PaymentsController : Controller
    {
        private readonly IPaymentService paymentService;
        private readonly IPaymentTypeService paymentTypeService;
        private readonly UserManager<User> userManager;
        private IHtmlSanitizer sanitizer;

        public PaymentsController(IPaymentService _paymentService, IPaymentTypeService _paymentTypeService, UserManager<User> _userManager)
        {
            paymentService = _paymentService;
            paymentTypeService = _paymentTypeService;
            userManager = _userManager;

            sanitizer = new HtmlSanitizer();
        }
        public async Task<IActionResult> Index()
        {
            var entities = await paymentTypeService.GetAllActivePaymentTypes();
            var models = entities.Select(x => new PaymentTypeViewModel()
            {
                Id = x.Id,
                Name = x.Name
            });

            return View(models);
        }

        public async Task<IActionResult> SelectPaymentType(int id)
        {
            var entity = await paymentTypeService.GetPaymentTypeAsync(id);
            if (entity != null)
            {
                var payments = await paymentService.GetAllActivePaymentsByTypeIdAsync(id);
                var model = new PaymentTypeViewModel()
                {
                    Id = entity.Id,
                    Name = entity.Name,
                    CurrentPayments = payments
                        .Select(p => new PaymentViewModel()
                        {
                            Id = p.Id,
                            Name = p.Name,
                            Description = p.Description,
                            Cost = p.Cost,
                            IsSignular = p.IsSignular,
                            IsPaidFor = p.IsPaidFor,
                        })
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Error", "Home", 
                    new ErrorViewModel() 
                    { 
                        Message = "Payment type not found." 
                    } );
            }
            
        }
        [HttpGet]
        public IActionResult AddCurrentPayment(int id)
        {
            var model = new PaymentViewModel();
            model.PaymentTypeId = id;

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddCurrentPayment(PaymentViewModel model)
        {


            var currentUser = await userManager.GetUserAsync(this.User);
            var entry = new CurrentPayment()
            {
                Name = sanitizer.Sanitize(model.Name),
                Description = sanitizer.Sanitize(model.Description),
                Cost = model.Cost,
                IsSignular = model.IsSignular,
                UserId = currentUser.Id,
                //TODO: Fix in the future. model.PaymentTypeId => model.Id for some reason
                PaymentTypeId = model.Id,
                IsActive = true,
                EntryDate = DateTime.Now,
            };

            await paymentService.AddCurrentPaymentAsync(entry);

            return RedirectToAction("SelectPaymentType", new { id = entry.PaymentTypeId });
        }

        [HttpGet]
        public IActionResult AddPaymentType()
        {
            var model = new PaymentTypeViewModel();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddPaymentType(PaymentTypeViewModel model)
        {
            var currentUser = await userManager.GetUserAsync(this.User);
            var entry = new PaymentType()
            {
                Name = sanitizer.Sanitize(model.Name),
                IsActive = true,
                UserId = currentUser.Id
            };

            await paymentTypeService.AddPaymentTypeAsync(entry);
            var paymentTypes = await paymentTypeService.GetAllActivePaymentTypes();
            var id = paymentTypes.Single(pt => pt.Name == entry.Name).Id;
            return RedirectToAction("SelectPaymentType", new { id });
        }

        [HttpGet]
        public async Task<IActionResult> DeletePaymentType(int id)
        {
            await paymentTypeService.DeletePaymentType(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DeletePayment(int id)
        {
            await paymentService.DeletePayment(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditPaymentType(int id)
        {
            var entity = await paymentTypeService.GetPaymentTypeAsync(id);
            var model = new PaymentTypeViewModel()
            {
                Id = entity.Id,
                Name = entity.Name,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditPaymentType(PaymentTypeViewModel model)
        {
            model.Name = sanitizer.Sanitize(model.Name);

            var entity = await paymentTypeService.GetPaymentTypeAsync(model.Id);
            entity.Name = model.Name;


            await paymentTypeService.SaveChangesToPaymentTypeAsync();

            return RedirectToAction("SelectPaymentType", new { id = model.Id });
        }


        public async Task<IActionResult> PayForPayment(int id)
        {
            await paymentService.PayForPayment(id);

            return RedirectToAction("Index", "Dashboard");
        }

        public async Task<IActionResult> UndoPayment(int id)
        {
            await paymentService.UndoPayment(id);

            return RedirectToAction("Index", "Dashboard");
        }

    }
}

FinanceApp/Controllers/ViewComponents/PaymentTypeLoadViewComponent.cs
using FinanceApp.Core.Contracts;
using FinanceApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinanceApp.Controllers.ViewComponents
{
    public class PaymentTypeLoadViewComponent : ViewComponent
    {
        private readonly IPaymentTypeService paymentTypeService;

        public PaymentTypeLoadViewComponent(IPaymentTypeService paymentTypeService)
        {
            this.paymentTypeService = paymentTypeService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var entities = await paymentTypeService.GetAllActivePaymentTypes();
            if (entities != null)
            {
                var models = entities.Select(e => new PaymentTypeViewModel()
                {
                    Id = e.Id,
                    Name = e.Name,
                });
                return View(models);
            }
            else
            {
                var models = new List<PaymentTypeViewModel>();
                return View(models);
            }
        }

    }
}

FinanceApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Finance App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinanceApp.Core.styles.css" asp-append-version="true" />
</head>
<body>
    <header style="background-color: #032B44">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" >
            <div class="container-fluid">
                <a class="navbar-brand" style="color: white" asp-area="" asp-controller="Home" asp-action="Index">Finance App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <div class="dropdown">
                                    <a class="btn text-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" style="background-color: #032B44" aria-expanded="false">
                                    Payments
                                  </a>

                                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item" asp-controller="Payments" asp-action="Index">Main</a></li>
                                        @await Component.InvokeAsync("PaymentTypeLoad")
                                  </ul>
                                </div>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="History" asp-action="Index">History</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="History" asp-action="Undo">Undo</a>
                            </li>
                        }
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer mt-auto py-3 position-fixed bottom-0 w-100">
          <div class="container">
            <span class="text-white">&copy; All rights reserved @DateTime.Now.Year - FinanceApp -</span>
          </div>
    </footer>
    


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>